openapi: 3.0.3
info:
  title: Cases
  description: API to make CRUD operations for the cases
  version: "1.0"
servers:
- url: http://localhost:8088
paths:
  /api/cases/add:
    post:
      tags:
      - cases
      summary: add cases
      operationId: cases#add
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AddRequestBody'
            example:
              collected: 0.8003833617014785
              currency: Sunt libero ullam nam voluptatem quis.
              desc: Qui officia non ipsa accusantium facilis consectetur.
              tags:
              - Quisquam vel deserunt.
              - Enim esse voluptas.
              - Ut quia ratione ipsa repellat.
              target: 0.34487022127545675
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AddResponse'
              example:
                desc: Quia nemo expedita autem at in iste.
        "401":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidScopes'
              example: Quis earum omnis enim.
  /api/cases/get:
    get:
      tags:
      - cases
      summary: get cases
      operationId: cases#get
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GetRequestBody'
            example:
              token: Est esse id.
      responses:
        "200":
          description: ""
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GetResponse'
                example:
                - Collected: 0.08528366918654866
                  Currency: Nam deserunt sit omnis sapiente numquam.
                  DateModified: Architecto vel veritatis cupiditate cupiditate suscipit.
                  Description: Qui non iusto dolor.
                  ID: 3569059227681456877
                  Tags:
                  - Quo est occaecati ducimus omnis qui voluptates.
                  - Et aut.
                  - Accusantium qui.
                  Target: 0.3494768250899328
                - Collected: 0.08528366918654866
                  Currency: Nam deserunt sit omnis sapiente numquam.
                  DateModified: Architecto vel veritatis cupiditate cupiditate suscipit.
                  Description: Qui non iusto dolor.
                  ID: 3569059227681456877
                  Tags:
                  - Quo est occaecati ducimus omnis qui voluptates.
                  - Et aut.
                  - Accusantium qui.
                  Target: 0.3494768250899328
                - Collected: 0.08528366918654866
                  Currency: Nam deserunt sit omnis sapiente numquam.
                  DateModified: Architecto vel veritatis cupiditate cupiditate suscipit.
                  Description: Qui non iusto dolor.
                  ID: 3569059227681456877
                  Tags:
                  - Quo est occaecati ducimus omnis qui voluptates.
                  - Et aut.
                  - Accusantium qui.
                  Target: 0.3494768250899328
              example:
              - Collected: 0.08528366918654866
                Currency: Nam deserunt sit omnis sapiente numquam.
                DateModified: Architecto vel veritatis cupiditate cupiditate suscipit.
                Description: Qui non iusto dolor.
                ID: 3569059227681456877
                Tags:
                - Quo est occaecati ducimus omnis qui voluptates.
                - Et aut.
                - Accusantium qui.
                Target: 0.3494768250899328
              - Collected: 0.08528366918654866
                Currency: Nam deserunt sit omnis sapiente numquam.
                DateModified: Architecto vel veritatis cupiditate cupiditate suscipit.
                Description: Qui non iusto dolor.
                ID: 3569059227681456877
                Tags:
                - Quo est occaecati ducimus omnis qui voluptates.
                - Et aut.
                - Accusantium qui.
                Target: 0.3494768250899328
        "401":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidScopes'
              example: Quo veritatis est dolores accusantium sed voluptas.
        "403":
          description: ""
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/InvalidScopes'
              example: Pariatur eum autem qui.
components:
  schemas:
    AddRequestBody:
      type: object
      properties:
        collected:
          type: number
          description: Collected Quantity
          example: 0.7764258062996218
          format: double
        currency:
          type: string
          description: Currency
          example: Vero odit itaque numquam eaque dolore.
        desc:
          type: string
          description: Case Description
          example: Error rerum ut dignissimos sit assumenda.
        tags:
          type: array
          items:
            type: string
            example: Ullam laboriosam quae rerum animi nobis non.
          description: Tags array
          example:
          - Earum unde a.
          - Distinctio laborum accusantium.
          - Dolorum ratione sed et eaque debitis.
          - Magni beatae itaque accusantium modi incidunt.
        target:
          type: number
          description: Target Quantity
          example: 0.5322072757169997
          format: double
      example:
        collected: 0.03605662069340875
        currency: Debitis dolor vel vel.
        desc: Modi vero sit sed iste.
        tags:
        - Et voluptate est accusantium ad nisi laboriosam.
        - Eveniet voluptates.
        - Magni consequatur corrupti.
        - Doloremque tempore beatae.
        target: 0.08709858501008473
      required:
      - desc
      - target
      - collected
      - currency
    AddResponse:
      type: object
      properties:
        desc:
          type: string
          description: The description of the case
          example: In exercitationem cupiditate illo quae.
      example:
        desc: Quod vitae non mollitia aliquam.
    GetRequestBody:
      type: object
      properties:
        token:
          type: string
          description: JWT used for authentication
          example: Aut ut.
      example:
        token: Consequuntur et quia reprehenderit a similique magni.
      required:
      - token
    GetResponse:
      type: object
      properties:
        Collected:
          type: number
          description: Collected value
          example: 0.7791250716157548
          format: double
        Currency:
          type: string
          description: Currency
          example: Iste voluptatem id ut repellat id neque.
        DateModified:
          type: string
          description: Date Modified in the database
          example: Mollitia et rem et officia explicabo.
        Description:
          type: string
          description: Case Description
          example: Vitae nemo pariatur.
        ID:
          type: integer
          description: Case ID
          example: 15081498803769119381
        Tags:
          type: array
          items:
            type: string
            example: Enim eos eius a.
          description: Tags
          example:
          - Tenetur adipisci qui veritatis doloribus.
          - Maxime voluptas provident totam.
        Target:
          type: number
          description: Targetted value
          example: 0.6636561037715235
          format: double
      example:
        Collected: 0.3938071993901215
        Currency: Omnis rerum nihil cupiditate.
        DateModified: Consequatur quia et eaque.
        Description: Et nobis debitis qui dolores eaque sapiente.
        ID: 9791146395616622828
        Tags:
        - Et aliquid ut hic.
        - Sit voluptatum asperiores unde amet.
        - Accusantium ex doloribus minus.
        Target: 0.6292243319016901
    InvalidScopes:
      type: string
      description: Token scopes are invalid
      example: Eos et labore molestiae.
